default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['PG_HOST'] %>
  username: <%= ENV['PG_USER'] || postgres %>
  password: <%= ENV['PG_PASSWORD'] || '' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  pool: 5

development:
  <<: *default
  database: gamble_system_development

test:
  <<: *default
  database: gamble_system_test

preparing:
  <<: *default
  database: gamble_system_preparing

production:
  <<: *default
  database: gamble_system_production
