development: &development
  host: localhost
  adapter: postgresql
  encoding: utf8  
  database: gamble_system_development
  pool: 5
  username: <%= Secret.database[:username] %>
  password: <%= Secret.database[:password] %>

test:
  <<: *development
  database: gamble_system_test

preparing:
  <<: *development
  database: gamble_system_preparing
  username: <%= Secret.database[:username] %>
  password: <%= Secret.database[:password] %>

production:
  <<: *development
  database: gamble_system_production
  username: <%= Secret.database[:username] %>
  password: <%= Secret.database[:password] %>