development: &development
  basic:
    - "rgba(2,119,189 ,0.9)"
    - "rgba(2,119,189 ,0.7)"
    - "rgba(2,119,189 ,0.3)"
    - "rgba(255,61,0 ,0.3)"
    - "rgba(255,61,0 ,0.7)"
    - "rgba(255,61,0 ,0.9)"
  other:
    - "#f44336"
    - "#9C27B0"
    - "#3F51B5"
    - "#00BCD4"
    - "#4CAF50"
    - "#CDDC39"
    - "#FFC107"
    - "#9E9E9E"
    - "#607D8B"
    - "#E91E63"
    - "#673AB7"
    - "#2196F3"
    - "#009688"
    - "#8BC34A"
    - "#FFEB3B"
    - "#FF5722"
    - "#795548"

test:
  <<: *development

preparing:
  <<: *development

production:
  <<: *development