development: &development
  default:
    settings:
      players: 4
      games: 10
    room:
      name: "範例群組"
    players:
      - name: "蔡英文"
        nickname: "V"
      - name: "柯文哲"
        nickname: "P"
      - name: "韓國瑜"
        nickname: "X"
      - name: "川普"
        nickname: "US"
      - name: "東錢"
        nickname: "$"
    games:
      - "2019-01-10"
      - "2019-02-12"
      - "2019-02-13"
      - "2019-02-14"
      - "2019-03-22"
      - "2019-05-18"
      - "2019-05-31"
      - "2019-07-01"
      - "2019-07-02"
      - "2019-09-10"
    records:
      - #1
        - 100 
        - 0
        - 200
        - -500
        - 200
      - #2
        - 400
        - 1200
        - -2000
        - 400
        - 200
      - #3
        - 1040
        - -940
        - 0
        - 0
        - -100
      - #4
        - 0
        - 0
        - -1200
        - 1000
        - 200
      - #5
        - 400
        - 800
        - 0
        - -1400
        - 200
      - #6
        - 100
        - 100
        - -400
        - 100
        - 100
      - #7
        - 3500
        - -1000
        - -2000
        - -700
        - 200
      - #8
        - 400
        - 1000
        - -1600
        - 0
        - 200
      - #9
        - 100
        - -1000
        - 0
        - 700
        - 200
      - #10
        - 0
        - 500
        - 500
        - -1200
        - 200



    


test:
  <<: *development

preparing:
  <<: *development

production:
  <<: *development