development: &development
  liff_entry: "1653880740-r34PQk4w"

test:
  <<: *development

staging:
  <<: *development
  liff_entry: "1653880740-N3nkQznA"

production:
  <<: *development
  liff_entry: "1653880740-Y1JWZlJO"
