development: &development
  liff_entry: '1653819226-983J3lAQ'

test:
  <<: *development

preparing:
  <<: *development
  liff_entry: '1653880740-N3nkQznA'

production:
  <<: *development
  liff_entry: '1653880740-Y1JWZlJO'