development: &development
  liff_entry: '1653819226-dOlol0nB'

test:
  <<: *development

preparing:
  <<: *development
  liff_entry: '1653819226-1O4O47YV'

production:
  <<: *development
  liff_entry: '1653819226-kZJmJaMd'